/**
 * Seed loads for demo mode — the backbone every dashboard reads. The demo backend
 * (lib/demo/domains/core.ts) turns these into `loads` rows; other seeds reference them by id.
 */
import type { Load } from '@freightx/shared';
import { daysFromNow, hoursAgo } from '@/lib/demo/time';

const BROKER_ID = 'demo-broker';
const SHIPPER_ID = 'demo-shipper';
const DRIVER_ID = 'demo-driver';
const DRIVER_2_ID = 'demo-driver-2';
const DRIVER_3_ID = 'demo-driver-3';

// Mixed statuses so every role's dashboard has something to act on.
export const DEMO_LOADS: Load[] = [
  {
    id: 'load-001',
    loadNumber: 'FX-1042',
    postedBy: BROKER_ID,
    companyId: 'demo-company-broker',
    companyName: 'Apex Freight Solutions',
    originCity: 'Atlanta',
    originState: 'GA',
    destCity: 'Dallas',
    destState: 'TX',
    pickupDate: daysFromNow(-1),
    deliveryDate: daysFromNow(1),
    equipment: 'van',
    commodity: 'Electronics',
    weightLbs: 38000,
    rateUsd: 3200,
    ratePerMile: 2.48,
    totalMiles: 1290,
    status: 'in_transit',
    bidCount: 4,
    assignedDriverId: DRIVER_ID,
    driverName: 'Carlos Mendez',
    postedAt: hoursAgo(48),
    brokerCreditScore: 92,
  },
  {
    id: 'load-002',
    loadNumber: 'FX-1043',
    postedBy: BROKER_ID,
    companyId: 'demo-company-broker',
    companyName: 'Apex Freight Solutions',
    originCity: 'Nashville',
    originState: 'TN',
    destCity: 'Chicago',
    destState: 'IL',
    pickupDate: daysFromNow(1),
    deliveryDate: daysFromNow(2),
    equipment: 'reefer',
    commodity: 'Produce',
    weightLbs: 42000,
    rateUsd: 2850,
    ratePerMile: 3.12,
    totalMiles: 914,
    status: 'awarded',
    bidCount: 3,
    assignedDriverId: undefined,
    driverName: undefined,
    postedAt: hoursAgo(24),
    brokerCreditScore: 88,
  },
  {
    id: 'load-003',
    loadNumber: 'FX-1044',
    postedBy: BROKER_ID,
    companyId: 'demo-company-broker',
    companyName: 'Apex Freight Solutions',
    originCity: 'Los Angeles',
    originState: 'CA',
    destCity: 'Phoenix',
    destState: 'AZ',
    pickupDate: daysFromNow(2),
    deliveryDate: daysFromNow(3),
    equipment: 'flatbed',
    commodity: 'Steel Coils',
    weightLbs: 44000,
    rateUsd: 1850,
    ratePerMile: 2.85,
    totalMiles: 649,
    status: 'posted',
    bidCount: 0,
    postedAt: hoursAgo(6),
    brokerCreditScore: 95,
  },
  {
    id: 'load-004',
    loadNumber: 'FX-1045',
    postedBy: SHIPPER_ID,
    companyId: 'demo-company-shipper',
    companyName: 'Park Manufacturing Co',
    originCity: 'Miami',
    originState: 'FL',
    destCity: 'Charlotte',
    destState: 'NC',
    pickupDate: daysFromNow(-1),
    deliveryDate: daysFromNow(0),
    equipment: 'van',
    commodity: 'Auto Parts',
    weightLbs: 35000,
    rateUsd: 2400,
    ratePerMile: 2.61,
    totalMiles: 920,
    status: 'delivered',
    bidCount: 5,
    assignedDriverId: DRIVER_3_ID,
    driverName: 'Luis Ortega',
    postedAt: hoursAgo(72),
    brokerCreditScore: 90,
  },
  {
    id: 'load-005',
    loadNumber: 'FX-1046',
    postedBy: BROKER_ID,
    companyId: 'demo-company-broker',
    companyName: 'Apex Freight Solutions',
    originCity: 'Houston',
    originState: 'TX',
    destCity: 'Memphis',
    destState: 'TN',
    pickupDate: daysFromNow(1),
    deliveryDate: daysFromNow(2),
    equipment: 'van',
    commodity: 'Consumer Goods',
    weightLbs: 40000,
    rateUsd: 1950,
    ratePerMile: 2.72,
    totalMiles: 717,
    status: 'bid_received',
    bidCount: 6,
    postedAt: hoursAgo(12),
    brokerCreditScore: 85,
  },
  {
    id: 'load-006',
    loadNumber: 'FX-1047',
    postedBy: SHIPPER_ID,
    companyId: 'demo-company-shipper',
    companyName: 'Park Manufacturing Co',
    originCity: 'Seattle',
    originState: 'WA',
    destCity: 'Portland',
    destState: 'OR',
    pickupDate: daysFromNow(3),
    deliveryDate: daysFromNow(4),
    equipment: 'step_deck',
    commodity: 'Machinery',
    weightLbs: 46000,
    rateUsd: 1200,
    ratePerMile: 3.45,
    totalMiles: 348,
    status: 'posted',
    bidCount: 0,
    postedAt: hoursAgo(3),
  },
  {
    id: 'load-007',
    loadNumber: 'FX-1048',
    postedBy: BROKER_ID,
    companyId: 'demo-company-broker',
    companyName: 'Apex Freight Solutions',
    originCity: 'Denver',
    originState: 'CO',
    destCity: 'Kansas City',
    destState: 'MO',
    pickupDate: daysFromNow(2),
    deliveryDate: daysFromNow(3),
    equipment: 'reefer',
    commodity: 'Frozen Foods',
    weightLbs: 39000,
    rateUsd: 2100,
    ratePerMile: 2.95,
    totalMiles: 712,
    status: 'dispatched',
    bidCount: 2,
    assignedDriverId: DRIVER_2_ID,
    driverName: 'Mike Johnson',
    postedAt: hoursAgo(36),
    brokerCreditScore: 91,
  },
  {
    id: 'load-008',
    loadNumber: 'FX-1049',
    postedBy: SHIPPER_ID,
    companyId: 'demo-company-shipper',
    companyName: 'Park Manufacturing Co',
    originCity: 'Detroit',
    originState: 'MI',
    destCity: 'Indianapolis',
    destState: 'IN',
    pickupDate: daysFromNow(-3),
    deliveryDate: daysFromNow(-2),
    equipment: 'van',
    commodity: 'Automotive Parts',
    weightLbs: 32000,
    rateUsd: 1100,
    ratePerMile: 2.55,
    totalMiles: 431,
    status: 'completed',
    bidCount: 3,
    assignedDriverId: DRIVER_ID,
    driverName: 'Carlos Mendez',
    postedAt: hoursAgo(120),
  },
  {
    id: 'load-009',
    loadNumber: 'FX-1050',
    postedBy: BROKER_ID,
    companyId: 'demo-company-broker',
    companyName: 'Apex Freight Solutions',
    originCity: 'Jacksonville',
    originState: 'FL',
    destCity: 'Savannah',
    destState: 'GA',
    pickupDate: daysFromNow(2),
    deliveryDate: daysFromNow(3),
    equipment: 'flatbed',
    commodity: 'Lumber',
    weightLbs: 43000,
    rateUsd: 950,
    ratePerMile: 2.68,
    totalMiles: 355,
    status: 'bid_received',
    bidCount: 4,
    postedAt: hoursAgo(8),
    brokerCreditScore: 87,
  },
  {
    id: 'load-010',
    loadNumber: 'FX-1051',
    postedBy: SHIPPER_ID,
    companyId: 'demo-company-shipper',
    companyName: 'Park Manufacturing Co',
    originCity: 'San Antonio',
    originState: 'TX',
    destCity: 'New Orleans',
    destState: 'LA',
    pickupDate: daysFromNow(0),
    deliveryDate: daysFromNow(1),
    equipment: 'van',
    commodity: 'Textiles',
    weightLbs: 28000,
    rateUsd: 1650,
    ratePerMile: 2.78,
    totalMiles: 594,
    status: 'in_transit',
    bidCount: 2,
    assignedDriverId: DRIVER_2_ID,
    driverName: 'Mike Johnson',
    postedAt: hoursAgo(48),
  },
];
